rethinkdb:
  image: rethinkdb
  ports:
    - "28015:28015"
    - "8080:8080"
  volumes:
    - data/:/data
horizon:
  image: rethinkdb/horizon
  command: su -s /bin/sh horizon -c "hz serve --connect rethinkdb:28015 --serve-static ./src/public --bind all /usr/app"
  volumes:
    - ./:/usr/app
  links:
    - rethinkdb
  ports:
    - "8181:8181"