# This is a TOML document

[collections.messages]
indexes = ["datetime"]

[groups.admin]
[groups.admin.rules.carte_blanche]
template = "any()"

# Allow users in the group "default" (all users, authenticated or not) to perform any read operation on `messages`:
[groups.default.rules.read_messages]
template = "collection('messages').anyRead()"

# Allow users in the group "default" (all users, authenticated or not) to perform any write operation on `messages`:
[groups.default.rules.write_messages]
template = "collection('messages').anyWrite()"
